ojpp_common/urls.py
from django.shortcuts import redirect
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

from ojpp_common.rest_views import router
from ojpp_common.views import *

urlpatterns = [
    path('', lambda r: redirect('/operators?active=true')),

    path('legal', TemplateView.as_view(template_name='legal.html')),
    path('stats', StatsView.as_view(), name='stats'),
    path('about', TemplateView.as_view(template_name='about.html')),
    path('map', TemplateView.as_view(template_name='location_map.html')),
    path('locations', RedirectView.as_view(url='/map')),

    path('api/stop_locations', StopLocationsView.as_view()),
    path('api/stop_locations/<int:pk>/arrivals', StopLocationsArrivalsView.as_view()),
    path('api/vehicle_locations', VehicleLocationsView.as_view()),
    path('operators', OperatorListView.as_view(), name='operator_list'),
    path('operators/<int:pk>', OperatorDetailView.as_view(), name='operator_detail'),
    path('vehicles', VehicleListView.as_view(), name='vehicle_list'),
    path('vehicles/<int:pk>', VehicleView.as_view(), name='vehicle_detail'),
    path('routes', RouteListView.as_view(), name='route_list'),
    path('routes/<int:pk>', RouteDetailView.as_view(), name='route_detail'),
    path('trips', TripFilterView.as_view(), name='trip_list'),
    path('trips/<int:pk>', TripDetailView.as_view(), name='trip_detail'),
    #path('tripinstances', TripInstanceFilterView.as_view(), name='tripinstance_list'),
    path('tripinstances/active', ActiveTripInstanceListView.as_view(), name='tripinstance_active'),
    path('tripinstances/<int:pk>', TripInstanceDetailView.as_view(), name='tripinstance_detail'),
    path('stops', StopListView.as_view(), name='stop_list'),
    path('stops/<int:pk>', StopDetailView.as_view(), name='stop_detail'),
    path('stop_locations', StopLocationListView.as_view(), name='stop_location_list'),
    path('stop_locations/datatables', StopLocationsDatatableView.as_view(), name='stop_location_list_datatables'),
    path('stop_locations/<int:pk>', StopLocationDetailView.as_view(), name='stop_location_detail'),
    path('schedules', ScheduleListView.as_view(), name='schedule_list'),
    path('schedules/<int:pk>', ScheduleDetailView.as_view(), name='schedule_detail'),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]


urlconf = urlpatterns, 'ojpp_common', 'ojpp_common'

ojpp_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from ojpp_common.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('ojpp_common.urls')),
    path('', include('django_prometheus.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

urlpatterns += [path(r"images-handler/", include("galleryfield.urls"))]

ojpp_common/models.py
import logging

from colorfield.fields import ColorField
from computedfields.models import computed, ComputedFieldsModel
from django.contrib.gis.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from galleryfield.fields import GalleryField
from psqlextra.models import PostgresModel
from django.contrib.gis.geos import Point, LineString, MultiLineString


class Stop(PostgresModel, ComputedFieldsModel):
    location = models.PointField(null=True)
    marprom_id = models.PositiveIntegerField(unique=True, db_index=True, blank=True, null=True)
    ijpp_id = models.PositiveIntegerField(unique=True, db_index=True, blank=True, null=True)
    lpp_id = models.PositiveIntegerField(unique=True, db_index=True, blank=True, null=True)
    name = models.CharField(max_length=50, null=True)
    is_active = models.BooleanField(default=True)

    @computed(models.PositiveSmallIntegerField(default=0), depends=[('stoplocation_set', ['id'])])
    def location_count(self):
        if self.id is not None:
            return self.stoplocation_set.count()
        return 0

    def get_absolute_url(self):
        return reverse('stop_detail', kwargs=dict(pk=self.id))

    def __str__(self):
        return self.name


class StopLocation(PostgresModel):
    stop = models.ForeignKey(Stop, on_delete=models.CASCADE, null=True)
    marprom_id = models.PositiveIntegerField(unique=True, db_index=True, blank=True, null=True)
    ijpp_id = models.PositiveIntegerField(unique=True, db_index=True, blank=True, null=True)
    lpp_id = models.PositiveIntegerField(unique=True, db_index=True, blank=True, null=True)
    location = models.PointField(null=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    photo = models.ImageField(null=True, blank=True)
    operator_stop_id = models.CharField(max_length=10, null=True, blank=True)

    def details_dict(self):
        return {
            'id': self.id,
            'name': self.name if self.name else self.stop.name,
            'marprom_id': self.marprom_id,
            'ijpp_id': self.ijpp_id,
            'lpp_id': self.lpp_id,
            'location': {
                'lat': self.location.y,
                'lon': self.location.x,
            },
            'stop_group_id': self.stop.id,
        }
    def __str__(self):
        return f'{self.stop.name if self.stop else "??"} - {self.name}'

    def get_absolute_url(self):
        return reverse('stop_location_detail', kwargs=dict(pk=self.id))

    def get_routes(self):
        return Route.objects.filter(trip__stoptime__stop_location=self).distinct()


class Operator(PostgresModel, ComputedFieldsModel):
    name = models.CharField(max_length=100, null=True)
    short_name = models.CharField(max_length=50, null=True, blank=True)
    slug = models.SlugField(max_length=100, unique=True, null=True)
    ijpp_avl_id = models.CharField(max_length=100, db_index=True, verbose_name='IJPP AVL ID', help_text='VehicleRef', unique=True)
    ijpp_id = models.PositiveIntegerField(unique=True, null=True, blank=True)
    ijpp_šifra = models.CharField(max_length=4, db_index=True, verbose_name='IJPP šifra', unique=True, blank=True, null=True)
    # nap_id = models.CharField(max_length=57, null=True, blank=True, db_index=True, unique=True)
    logo = models.ImageField(null=True, blank=True)
    logo_square = models.ImageField(null=True, blank=True)
    color = ColorField(default='#444444', null=True, blank=True)
    active = models.BooleanField(default=True)
    website = models.URLField(null=True, blank=True)
    tax_id = models.CharField(max_length=10, null=True, blank=True)

    aliases = models.CharField(max_length=100, null=True, blank=True)
    notes = models.TextField(blank=True, null=True)

    def get_short_name(self):
        return self.short_name if self.short_name else self.name

    class Meta:
        ordering = ('name',)

    def get_absolute_url(self):
        return reverse('operator_detail', kwargs=dict(pk=self.id))

    def __str__(self):
        return self.name

    def get_logo(self):
        return self.logo.url if self.logo else self.logo_square.url if self.logo_square else None

    def get_short_name(self):
        return self.short_name if self.short_name else self.name.replace('d.o.o.', '').strip(' ,.')


class RouteGroup(PostgresModel):
    number = models.CharField(max_length=5, null=True, blank=True)
    operator = models.ForeignKey(Operator, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True, blank=True)
    color = ColorField(default='#444444')

    marprom_id = models.PositiveIntegerField(unique=True, db_index=True, blank=True, null=True)

    def __str__(self):
        return f'{self.number}: {self.name}'


class Route(ComputedFieldsModel, PostgresModel):
    active = models.BooleanField(default=True)

    name = models.CharField(max_length=250, null=True, blank=True)
    name_via = models.CharField(max_length=250, null=True, blank=True)
    operator = models.ForeignKey(Operator, on_delete=models.CASCADE, related_name='routes')
    route_group = models.ForeignKey(RouteGroup, on_delete=models.CASCADE, null=True, blank=True)

    ijpp_id = models.PositiveIntegerField(unique=True, blank=True, null=True)
    marprom_id = models.CharField(max_length=100, unique=True, db_index=True, blank=True, null=True)
    lpp_id = models.CharField(max_length=36, null=True, blank=True)

    nvr_name = models.CharField(max_length=100, null=True, blank=True)
    nvr_number = models.CharField(max_length=16, null=True, blank=True)
    nvr_version = models.CharField(max_length=8, null=True, blank=True)

    route_type = models.CharField(max_length=50, null=True, blank=True)

    note = models.TextField(null=True, blank=True)

    def get_name(self):
        if self.name:
            return self.name
        try:
            return self.first_stop.name + ' - ' + self.last_stop.name
        except AttributeError:
            return '#%s' % self.id

    def save(
        self,
        force_insert = False,
        force_update = False,
        using = None,
        update_fields = None,
        skip_computedfields = False
    ) -> None:

        super().save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields,
            skip_computedfields=skip_computedfields or self.id is None
        )

    def __str__(self):
        return f'#{self.id}'

    def get_absolute_url(self):
        return reverse('route_detail', kwargs=dict(pk=self.id))

    @computed(models.ForeignKey(Stop, on_delete=models.SET_NULL, null=True, related_name='_first_stop'), depends=[('trips', ['id'])])
    def first_stop(self):
        try:
            return self.trips.first().stoptimes.order_by('sequence_num').first().stop_location.stop.id
        except AttributeError:
            return None

    @computed(models.ForeignKey(Stop, on_delete=models.SET_NULL, null=True, related_name='_last_stop'), depends=[('trips', ['id'])])
    def last_stop(self):
        try:
            return self.trips.first().stoptimes.order_by('sequence_num').last().stop_location.stop.id
        except AttributeError:
            return None

    def geometry(self):
        try:
            return MultiLineString(LineString([
                st.stop_location.location
                for st in self.trips.first().stoptimes.order_by('sequence_num').prefetch_related('stop_location') if st.stop_location.location
            ]))
        except AttributeError:
            return None


class RouteSegment(PostgresModel):
    active = models.BooleanField(default=True)

    start_stop = models.ForeignKey(StopLocation, on_delete=models.CASCADE, related_name='segments_start')
    end_stop = models.ForeignKey(StopLocation, on_delete=models.CASCADE, related_name='segments_end')
    time = models.DurationField(null=True, blank=True)
    length = models.FloatField(null=True, blank=True)
    ijpp_id = models.PositiveIntegerField(unique=True, blank=True, null=True)
    ijpp_geometry = models.LineStringField(srid=4326, null=True, blank=True)
    osm_geometry = models.LineStringField(srid=4326, null=True, blank=True)

class Trip(ComputedFieldsModel, PostgresModel):
    active = models.BooleanField(default=True)

    ijpp_id = models.PositiveIntegerField(unique=True, blank=True, null=True)
    piran_id = models.PositiveIntegerField(unique=True, null=True, blank=True)
    marprom_id = models.PositiveIntegerField(unique=True, db_index=True, blank=True, null=True)
    route = models.ForeignKey(Route, on_delete=models.CASCADE, null=True, blank=True, related_name='trips')
    seq_number = models.PositiveSmallIntegerField(null=True, blank=True)
    geometry = models.LineStringField(srid=4326, null=True, blank=True)
    geometry_is_final = models.BooleanField(default=False)
    schedule = models.ForeignKey('Schedule', on_delete=models.SET_NULL, null=True, blank=True)
    headsign = models.CharField(max_length=256, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('trip_detail', kwargs=dict(pk=self.id))

    @computed(models.CharField(blank=True, null=True, max_length=300), depends=[('route', ['name']), ('stoptimes', ['id'])])
    def name(self):
        try:
            if self.route_id is None:
                return '#' + str(self.id)
            #if self.route.name:
            #    return self.route.name
            else:
                st = self.stoptimes.order_by('sequence_num').select_related('stop_location__stop')
                if self.stoptimes.exists():
                    return f'{st.first().stop_location.stop.name} - {st.last().stop_location.stop.name}'
                else:
                    return '#' + str(self.id)
        except:
            logging.exception('Error calculating trip name')
            return '#' + str(self.id)

ojpp_common/templates/ojpp_common/active_tripinstance_list.html
{% extends "base.html" %}
{% block css %}
    {{ block.super }}
    {% include "partials/datatables.html" %}
{% endblock css %}
{% block main %}
    <h2 class="is-size-2">Active trips (last 24h)</h2>

    <table class="table is-fullwidth" id="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Operator</th>
            <th>Trip</th>
            <th>Last stop</th>
        </tr>
        </thead>
        {% for tripinstance in object_list %}
            <tr>
                <td><a href="{{ tripinstance.get_absolute_url }}">{{ tripinstance.id }}</a></td>
                <td><a href="{{ tripinstance.vehicle.operator.get_absolute_url }}">{{ tripinstance.vehicle.operator.name }}</a></td>
                <td><a href="{{ tripinstance.trip.get_absolute_url }}">{{ tripinstance.trip.name }}</a></td>
                <td>{{ tripinstance.last_stop_arrival }}</td>
            </tr>
        {% endfor %}
    </table>
    <script>
        var table = $('#table').DataTable({
            paging: false,
            fixedHeader: {
                header: true
            },
        });
    </script>
{% endblock %}

ojpp_common/templates/ojpp_common/operator_list.html
{% extends "base.html" %}
{% block title %}Operators{% endblock %}
{% block css %}
    {{ block.super }}
    {% include "partials/datatables.html" %}
{% endblock css %}

{% block main %}
    <div class="buttons has-addons">
        <a href="?active=true" class="button{% if filter.form.active.value %} is-info is-selected{% endif %}">Aktivni</a>
        <a href="?active=" class="button{% if not filter.form.active.value %} is-info is-selected{% endif %}">Vsi</a>
    </div>
    <table class="table is-fullwidth" id="table">
        <thead>
        <tr>
            <th></th>
            <th>Naziv operaterja</th>
            <th>Št. vozil</th>
            <th>Št. linij</th>
        </tr>
        </thead>

        {% for operator in object_list %}
            <tr>
                <td><img src="{{ operator.get_logo }}" alt=""></td>
                <td><a href="{{ operator.get_absolute_url }}">{{ operator.name }}</a></td>
                <td>{{ operator.vehicles__count }}</td>
                <td>{{ operator.routes__count }}</td>
            </tr>
        {% endfor %}
    </table>
    <script>
        var table = $('#table').DataTable({
            paging: false,
            fixedHeader: {
                header: true
            },
        });
    </script>
    <style>
        #table img {
            max-height: 1rem;
        }

        #table tr td:first-child {
            width: 10%;
        }
    </style>
{% endblock %}

ojpp_common/templates/ojpp_common/route_list.html
{% extends "base.html" %}
{% load ojpp_common %}
{% block title %}Routes{% endblock %}
{% block css %}
    {{ block.super }}
    {% include "partials/datatables.html" %}
{% endblock css %}

{% block main %}
    <h2 class="is-size-2">Route list</h2>

    <table class="table is-fullwidth" id="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Prva postaja</th>
                <th>Zadnja postaja</th>
                <th>Naziv linije</th>
                <th>Naziv operatorja</th>
            </tr>
        </thead>

        {% for route in object_list %}
            <tr>
                <td>{% ojpp_link route route.id %}</td>
                <!--<td><a href="{{ route.get_absolute_url }}">{{ route.id }}</a></td>-->
                <td><a href="{{ route.first_stop.get_absolute_url }}">{{ route.first_stop.name }}</a></td>
                <td><a href="{{ route.last_stop.get_absolute_url }}">{{ route.last_stop.name }}</a></td>
                <td><a href="{{ route.get_absolute_url }}">{{ route.name }}</a></td>
                <td><a href="{{ route.operator.get_absolute_url }}">{{ route.operator.name }}</a></td>
            </tr>
        {% endfor %}
    </table>
    <script>
        var table = $('#table').DataTable({
            paging: true,
            pageLength: 100,
            fixedHeader: {
                header: true
            },
        });
    </script>
    <style>
    #table img {
        max-height: 1rem;
    }
    #table tr td:first-child {
        width: 10%;
    }
    </style>
{% endblock %}

ojpp_common/templates/ojpp_common/schedule_detail.html
{% extends "base.html" %}
{% block css %}
    {{ block.super }}
    <script src="https://unpkg.com/js-year-calendar@latest/dist/js-year-calendar.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/js-year-calendar@latest/dist/js-year-calendar.min.css" />
{% endblock css %}
{% block main %}
    <a href="{% url 'admin:ojpp_common_schedule_change' object_id=object.pk %}" class="button is-warning" style="float:right">Edit</a>
    <h2 class="is-size-2">{{ operator.name }}</h2>
    <hr>
    <div class="columns">
        <section class="column">
            <table class="table">
                <tr>
                    <th>ID</th>
                    <td>{{ object.id }}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ object.name|default:"" }}</td>
                </tr>
                <tr>
                    <th>IJPP tag</th>
                    <td>{{ object.ijpp_tag|default:"" }}</td>
                </tr>
                <tr>
                    <th>IJPP ID</th>
                    <td>{{ object.ijpp_id|default:"" }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ object.description|default:"" }}</td>
                </tr>
                <tr>
                    <th>Used by</th>
                    <td><a href="/trips?schedule={{ object.id }}">{{ object.trip_set.count }} trips</a></td>
                </tr>
            </table>
        </section>
    </div>

    <section>
        <div id="calendar-element"></div>
    </section>

    <section>
        <h2 class="is-size-2">Structure</h2>

        <p><strong>Default state: </strong>{{ object.default_state|yesno:'✅,❌' }}</p>

        <div class="columns">
            <div class="column">
                <h3 class="is-size-3">Periods</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Set</th>
                        <th>From</th>
                        <th>To</th>
                        <th>Mo</th>
                        <th>Tu</th>
                        <th>We</th>
                        <th>Th</th>
                        <th>Fr</th>
                        <th>Sa</th>
                        <th>Su</th>
                        <th><abbr title="Public holidays">PH</abbr></th>
                    </tr>
                    </thead>
                    {% for period in object.periods.all %}
                        <tr>
                            <td>{{ period.action|yesno:'✅,❌' }}</td>
                            <td>{{ period.day_from|stringformat:'02d' }}. {{ period.month_from|stringformat:'02d' }}. {{ period.year_from|default:'____' }}</td>
                            <td>{{ period.day_to|stringformat:'02d' }}. {{ period.month_to|stringformat:'02d' }}. {{ period.year_to|default:'____' }}</td>
                            <td>{{ period.monday|yesno:'✅,❌' }}</td>
                            <td>{{ period.tuesday|yesno:'✅,❌' }}</td>
                            <td>{{ period.wednesday|yesno:'✅,❌' }}</td>
                            <td>{{ period.thursday|yesno:'✅,❌' }}</td>
                            <td>{{ period.friday|yesno:'✅,❌' }}</td>
                            <td>{{ period.saturday|yesno:'✅,❌' }}</td>
                            <td>{{ period.sunday|yesno:'✅,❌' }}</td>
                            <td>{{ period.holidays|yesno:'✅,❌' }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="column">
                <h3 class="is-size-3">Exceptions</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Set</th>
                        <th>Date</th>
                    </tr>
                    </thead>
                    {% for exception in object.exceptions.all %}
                        <tr>
                            <td>{{ exception.action|yesno:'✅,❌' }}</td>
                            <td>{{ exception.date|date:'d. m. Y' }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </section>

    <style>
        .day {
            background-color: hsl(0, 0%, 96%);
        }

        .calendar-header {
            display: none;
        }

        .calendar table.month td.day .day-content {
            border-radius: 0;
        }
    </style>
    <script>
        new Calendar('#calendar-element', {
            style: 'background',
            dataSource: [
                {% for date in days_active %}
                    {
                        startDate: new Date({{ date.year }}, {{ date.month }} - 1, {{ date.day }}),
                        endDate: new Date({{ date.year }}, {{ date.month }} - 1, {{ date.day }}),
                        color: 'hsl(141, 71%, 48%)'
                    },
                {% endfor %}
            ],
            weekStart: 1
        })
    </script>
{% endblock %}

ojpp_common/templates/ojpp_common/stats.html
{% extends "base.html" %}
{% block title %}{{ route.name }}{% endblock %}
{% block css %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@^3"></script>
    <script src="https://cdn.jsdelivr.net/npm/luxon@^2"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-luxon@^1"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-crosshair@1.2.0"></script>
{% endblock css %}
{% block main %}

    <section class="section is-main-section">
        <div class="tile is-ancestor">
            <div class="tile is-parent">
                <div class="card tile is-child">
                    <div class="card-content">
                        <div class="level is-mobile">
                            <div class="level-item">
                                <div class="is-widget-label"><h3 class="subtitle is-spaced">
                                    Vozila
                                </h3>
                                    <h1 class="title">
                                        {{ counts.vehicles }}
                                    </h1>
                                </div>
                            </div>
                            <div class="level-item has-widget-icon">
                                <div class="is-widget-icon"><span class="icon has-text-primary is-large"><i class="mdi mdi-account-multiple mdi-48px"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tile is-parent">
                <div class="card tile is-child">
                    <div class="card-content">
                        <div class="level is-mobile">
                            <div class="level-item">
                                <div class="is-widget-label"><h3 class="subtitle is-spaced">
                                    Routes
                                </h3>
                                    <h1 class="title">
                                        {{ counts.routes }}
                                    </h1>
                                </div>
                            </div>
                            <div class="level-item has-widget-icon">
                                <div class="is-widget-icon"><span class="icon has-text-info is-large"><i class="mdi mdi-cart-outline mdi-48px"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tile is-parent">
                <div class="card tile is-child">
                    <div class="card-content">
                        <div class="level is-mobile">
                            <div class="level-item">
                                <div class="is-widget-label"><h3 class="subtitle is-spaced">
                                    Stops
                                </h3>
                                    <h1 class="title">
                                        {{ counts.stop_locations }}
                                    </h1>
                                </div>
                            </div>
                            <div class="level-item has-widget-icon">
                                <div class="is-widget-icon"><span class="icon has-text-success is-large"><i class="mdi mdi-finance mdi-48px"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">
                    <span class="icon"><i class="mdi mdi-finance"></i></span>
                    Performance
                </p>
                <a href="#" class="card-header-icon">
                    <span class="icon"><i class="mdi mdi-reload"></i></span>
                </a>
            </header>
            <div class="card-content">
                <div class="chart-area">

                    <canvas id="chart2"></canvas>

                </div>
            </div>
        </div>
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">
                    <span class="icon"><i class="mdi mdi-finance"></i></span>
                    Performance
                </p>
                <a href="#" class="card-header-icon">
                    <span class="icon"><i class="mdi mdi-reload"></i></span>
                </a>
            </header>
            <div class="card-content">

                <canvas id="chart3"></canvas>

            </div>
        </div>
    </section>


    <style>

    </style>

    <script>


        var chart2 = new Chart(document.getElementById("chart2").getContext("2d"), {
            type: "line",
            options: {
                plugins: {
                    crosshair: {
                        sync: {
                            enabled: false
                        },
                    },
                    tooltip: {
                        animation: false,
                        mode: "interpolate",
                        intersect: false,
                        callbacks: {
                            title: function (a, d) {
                                return a[0].element.x.toFixed(2);
                            },
                            label: function (d) {
                                return (
                                    d.chart.data.datasets[d.datasetIndex].label + ": " + d.element.y.toFixed(2)
                                );
                            }
                        }
                    }
                },
                scales: {
                    x: {
                        type: "time",
                        time: {
                            unit: "hour",
                            // Luxon format string
                            tooltipFormat: "DD T",
                            displayFormats: {
                                hour: "d.M. h'h'"
                            }
                        },
                        title: {
                            display: true,
                            text: "Hour",
                        },
                    },
                    y: {
                        title: {
                            display: true,
                            text: "value",
                        },
                        ticks: {
                            stepSize: 1
                        }
                    },
                },
            },
            data: {
                datasets: [
                    {
                        "backgroundColor": "red",
                        "borderColor": "red",
                        "showLine": true,
                        "fill": false,
                        "pointRadius": 4,
                        "label": "Vehicles",
                        "data": [
                            {% for point in vehicle_locations %}
                                {
                                    "x": new Date({{ point.hour|date:"Y, m-1, d, H, m" }}),
                                    "y": {{ point.c }}
                                },
                            {% endfor %}
                        ],
                        "lineTension": 0,
                        "interpolate": false
                    }
                ]
            }
        });

    </script>
{% endblock %}

ojpp_common/templates/ojpp_common/stoplocation_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Stops{% endblock %}
{% block css %}
    {{ block.super }}
    {% include "partials/datatables.html" %}
    <script type="text/javascript" src="{% static 'ajax_datatable/js/utils.js' %}"></script>
    <link href="{% static 'ajax_datatable/css/style.css' %}" rel="stylesheet" />
{% endblock css %}

{% block main %}
    <div class="table-responsive">
    <table id="datatable" width="100%" class="table table-striped table-bordered dataTables-log">
    </table>
</div>

    <script>
        AjaxDatatableViewUtils.initialize_table(
            $('#datatable'),
            "{% url 'stop_location_list_datatables' %}",
            extra_option={
                paging: true,
                pageLength: 100,
                fixedHeader: {
                    header: true
                },
            },
            extra_data={}
        );

    </script>
    <style>
    #table img {
        max-height: 1rem;
    }
    #table tr td:first-child {
        width: 10%;
    }
    </style>
{% endblock %}